executor: slurm
#slurm-extra-args: "--exclude=pauli1"
#max-failures: 20

# Optional but common:
#default-resources:
  #slurm_partition: "compute"
  #slurm_account: "myacct"
  #runtime: 5         # minutes
  #mem_mb: 1000 # MB

# threads = --cpus-per-task on SLURM