# config/config.yaml

data_folder: "data"
base_name: "case"
digits_case_numbers: 2
case_numbers: 0 1 2
# "Config file config\config.yaml is extended by additional config specified via the command line." is printed if the command line includes e.g. --config case_number=0.
# If config is passed on the command line, it redefines the config key