name: default_environment
channels:
  - conda-forge
  - defaults
dependencies: # not tested yet. Just an example
  - python=3.12
  - numpy
  - matplotlib
  - pandas
  - networkx
  - pygraphviz

# part of the standard library: os, sys, math, pickle


